const sampleData = [
  {
    no: 1,
    fullName: 'John Doe',
    yearLevel: '1st Year',
    pgfAverage: 3.00,
    proficiency: 'Intermediate',

    consistency: 'Can produce neutral pronunciation throughout the conversation.',
    scoreConsistency: 4.00,
    clarity: 'Can have accent that does not cause misunderstanding of the speaker\'s message.',
    scoreClarity: 3.50,
    articulation: 'Can articulate vowels and consonants accurately.',
    scoreArticulation: 4.00,
    intonationAndStress: 'Can express in controlled and consistent intonation, stress, linking.',
    scoreIntonationAndStress: 3.50,
    pronunciationRating: 3.75,
    accuracy: 'Can communicate in simple and complex sentences and in scripted and authentic settings that are accurate all the time.',
    scoreAccuracy: 4.00,
    clarityOfThought: 'Can communicate clear and understandable meaning throughout the whole conversation.',
    scoreClarityOfThought: 4.00,
    syntax: 'Can have syntax that is accurate throughout the whole conversation.',
    scoreSyntax: 4.00,
    grammarRating: 4.00,
    qualityOfResponse: 'Can often satisfactorily answer and respond to scripted and non-scripted questions and settings.',
    scoreQualityOfResponse: 3.50,
    detailOfResponse: 'Can provide a response to a given prompt with SUFFICIENT INFORMATION.',
    scoreDetailOfResponse: 3.50,
    fluencyRating: 3.50,
  
  },
  {
    no: 2,
    fullName: 'Jane Smith',
    yearLevel: '2nd Year',
    pgfAverage: 3.20,
    proficiency: 'Advanced',

    consistency: 'Maintains consistent pronunciation with minimal errors.',
    scoreConsistency: 4.50,
    clarity: 'Clear articulation that enhances understanding.',
    scoreClarity: 4.20,
    articulation: 'Consistently articulates difficult sounds accurately.',
    scoreArticulation: 4.50,
    intonationAndStress: 'Uses varied intonation and appropriate stress effectively.',
    scoreIntonationAndStress: 4.30,
    pronunciationRating: 4.38,
    accuracy: 'Shows high accuracy in complex sentence structures.',
    scoreAccuracy: 4.50,
    clarityOfThought: 'Effectively conveys complex ideas with clarity.',
    scoreClarityOfThought: 4.50,
    syntax: 'Demonstrates flawless syntax.',
    scoreSyntax: 4.50,
    grammarRating: 4.50,
    qualityOfResponse: 'Provides insightful responses to non-scripted questions.',
    scoreQualityOfResponse: 4.40,
    detailOfResponse: 'Offers comprehensive and detailed responses.',
    scoreDetailOfResponse: 4.20,
    fluencyRating: 4.40,

  },
{
    no: 3,
    fullName: 'Michael Johnson',
    yearLevel: '1st Year',
    pgfAverage: 2.80,
    proficiency: 'Basic',

    consistency: 'Occasionally struggles with consistency under pressure.',
    scoreConsistency: 3.00,
    clarity: 'Understands spoken instructions with some difficulty.',
    scoreClarity: 2.80,
    articulation: 'Pronunciation errors are common.',
    scoreArticulation: 3.10,
    intonationAndStress: 'Limited use of intonation and stress patterns.',
    scoreIntonationAndStress: 2.90,
    pronunciationRating: 3.00,
    accuracy: 'Accuracy varies with familiarity of topics.',
    scoreAccuracy: 3.10,
    clarityOfThought: 'Requires prompting to clarify ideas.',
    scoreClarityOfThought: 3.00,
    syntax: 'Struggles with correct syntax in complex sentences.',
    scoreSyntax: 2.90,
    grammarRating: 3.00,
    qualityOfResponse: 'Responses are brief and lack depth.',
    scoreQualityOfResponse: 2.80,
    detailOfResponse: 'Provides limited details in responses.',
    scoreDetailOfResponse: 2.90,
    fluencyRating: 2.85,

},
{
    no: 4,
    fullName: 'Emily Davis',
    yearLevel: '3rd Year',
    pgfAverage: 3.75,
    proficiency: 'Proficient',

    consistency: 'Writes with a steady flow and few interruptions.',
    scoreConsistency: 4.20,
    clarity: 'Produces clear and coherent written work.',
    scoreClarity: 4.10,
    articulation: 'Articulates ideas effectively in written form.',
    scoreArticulation: 4.25,
    intonationAndStress: 'Not applicable in writing.',
    scoreIntonationAndStress: 3.75,
    pronunciationRating: 4.35,
    accuracy: 'Uses accurate grammar and vocabulary consistently.',
    scoreAccuracy: 4.30,
    clarityOfThought: 'Ideas are well-organized and logical.',
    scoreClarityOfThought: 4.40,
    syntax: 'Demonstrates excellent command of syntax.',
    scoreSyntax: 4.50,
    grammarRating: 4.50,
    qualityOfResponse: 'Responses are insightful and engaging.',
    scoreQualityOfResponse: 4.35,
    detailOfResponse: 'Provides detailed and well-supported arguments.',
    scoreDetailOfResponse: 4.40,
    fluencyRating: 4.35,

},
{
    no: 5,
    fullName: 'Chris Brown',
    yearLevel: '4th Year',
    pgfAverage: 3.50,
    proficiency: 'Intermediate',
    consistency: 'Maintains fluency but with occasional hesitations.',
    scoreConsistency: 3.80,
    clarity: 'Mostly clear but sometimes requires repetition.',
    scoreClarity: 3.70,
    articulation: 'Can articulate key phrases accurately.',
    scoreArticulation: 3.90,
    intonationAndStress: 'Demonstrates appropriate use of intonation.',
    scoreIntonationAndStress: 3.80,
    pronunciationRating: 3.80,
    accuracy: 'Occasionally struggles with advanced grammar.',
    scoreAccuracy: 3.70,
    clarityOfThought: 'Can express thoughts but with occasional redundancy.',
    scoreClarityOfThought: 3.85,
    syntax: 'Syntax is mostly accurate.',
    scoreSyntax: 3.80,
    grammarRating: 3.75,
    qualityOfResponse: 'Responses are relevant but could be more concise.',
    scoreQualityOfResponse: 3.70,
    detailOfResponse: 'Provides sufficient but not extensive details.',
    scoreDetailOfResponse: 3.80,
    fluencyRating: 3.75,

},
{
    no: 6,
    fullName: 'Sophia Martinez',
    yearLevel: '2nd Year',
    pgfAverage: 4.00,
    proficiency: 'Advanced',

    consistency: 'Always understands with high consistency.',
    scoreConsistency: 4.00,
    clarity: 'Effectively comprehends complex instructions.',
    scoreClarity: 4.40,
    articulation: 'Not applicable for listening.',
    scoreArticulation: 4.40,
    intonationAndStress: 'Not applicable for listening.',
    scoreIntonationAndStress: 4.45,
    pronunciationRating: 4.40,
    accuracy: 'Demonstrates precise understanding of nuanced language.',
    scoreAccuracy: 4.50,
    clarityOfThought: 'Easily synthesizes and explains information.',
    scoreClarityOfThought: 4.50,
    syntax: 'Not applicable for listening.',
    scoreSyntax: 4.50,
    grammarRating: 4.50,
    qualityOfResponse: 'Responds with relevant and accurate insights.',
    scoreQualityOfResponse: 4.40,
    detailOfResponse: 'Provides detailed summaries of heard information.',
    scoreDetailOfResponse: 4.50,
    fluencyRating: 4.45,

},
{
    no: 7,
    fullName: 'Liam Wilson',
    yearLevel: '3rd Year',
    pgfAverage: 3.10,
    proficiency: 'Intermediate',

    consistency: 'Occasionally falters during extended conversations.',
    scoreConsistency: 3.20,
    clarity: 'Speech is clear in familiar contexts.',
    scoreClarity: 3.30,
    articulation: 'Articulation is generally accurate.',
    scoreArticulation: 3.40,
    intonationAndStress: 'Basic use of intonation is present.',
    scoreIntonationAndStress: 3.25,
    pronunciationRating: 3.30,
    accuracy: 'Manages simple sentence structures effectively.',
    scoreAccuracy: 3.20,
    clarityOfThought: 'Can express basic ideas clearly.',
    scoreClarityOfThought: 3.30,
    syntax: 'Syntax errors are present but do not impede understanding.',
    scoreSyntax: 3.25,
    grammarRating: 3.30,
    qualityOfResponse: 'Responses are simple but appropriate.',
    scoreQualityOfResponse: 3.25,
    detailOfResponse: 'Provides basic details in responses.',
    scoreDetailOfResponse: 3.20,
    fluencyRating: 3.25,

},
{
    no: 8,
    fullName: 'Olivia Garcia',
    yearLevel: '1st Year',
    pgfAverage: 2.90,
    proficiency: 'Basic',

    consistency: 'Frequently inconsistent in writing clarity.',
    scoreConsistency: 2.80,
    clarity: 'Struggles to convey ideas clearly in writing.',
    scoreClarity: 2.70,
    articulation: 'Written articulation needs improvement.',
    scoreArticulation: 2.80,
    intonationAndStress: 'Not applicable in writing.',
    scoreIntonationAndStress: 2.90,
    pronunciationRating: 2.80,
    accuracy: 'Basic grammatical errors are frequent.',
    scoreAccuracy: 2.90,
    clarityOfThought: 'Ideas are fragmented and lack coherence.',
    scoreClarityOfThought: 2.70,
    syntax: 'Syntax issues often cause confusion.',
    scoreSyntax: 2.80,
    grammarRating: 2.85,
    qualityOfResponse: 'Responses are brief and lack depth.',
    scoreQualityOfResponse: 2.75,
    detailOfResponse: 'Limited details provided in written work.',
    scoreDetailOfResponse: 2.70,
    fluencyRating: 2.80,

},
{
    no: 9,
    fullName: 'Noah Harris',
    yearLevel: '4th Year',
    pgfAverage: 3.60,
    proficiency: 'Proficient',

    consistency: 'Reads with a steady pace and high comprehension.',
    scoreConsistency: 4.00,
    clarity: 'Understands and interprets text with clarity.',
    scoreClarity: 3.90,
    articulation: 'Accurately identifies key points in reading.',
    scoreArticulation: 4.00,
    intonationAndStress: 'Not applicable in reading.',
    scoreIntonationAndStress: 3.60,
    pronunciationRating: 3.90,
    accuracy: 'Comprehends and explains complex reading material.',
    scoreAccuracy: 4.10,
    clarityOfThought: 'Interprets and synthesizes ideas effectively.',
    scoreClarityOfThought: 4.20,
    syntax: 'Not applicable for reading.',
    scoreSyntax: 4.00,
    grammarRating: 4.00,
    qualityOfResponse: 'Responds with well-formed analysis.',
    scoreQualityOfResponse: 4.10,
    detailOfResponse: 'Provides insightful and detailed interpretations.',
    scoreDetailOfResponse: 4.20,
    fluencyRating: 4.15,

},
{
    no: 10,
    fullName: 'Isabella Thomas',
    yearLevel: '2nd Year',
    pgfAverage: 3.85,
    proficiency: 'Advanced',

    consistency: 'Highly consistent with minimal errors.',
    scoreConsistency: 4.40,
    clarity: 'Exceptionally clear speech that enhances communication.',
    scoreClarity: 4.50,
    articulation: 'Accurately articulates complex sounds.',
    scoreArticulation: 4.40,
    intonationAndStress: 'Uses varied intonation and stress effectively.',
    scoreIntonationAndStress: 4.50,
    pronunciationRating: 4.45,
    accuracy: 'Consistently accurate in grammar and vocabulary.',
    scoreAccuracy: 4.50,
    clarityOfThought: 'Communicates ideas concisely and effectively.',
    scoreClarityOfThought: 4.50,
    syntax: 'Demonstrates mastery of syntax.',
    scoreSyntax: 4.50,
    grammarRating: 4.50,
    qualityOfResponse: 'Responses are thoughtful and well-developed.',
    scoreQualityOfResponse: 4.45,
    detailOfResponse: 'Provides comprehensive and insightful responses.',
    scoreDetailOfResponse: 4.50,
    fluencyRating: 4.48,

}
];

export default sampleData;
